### ISSUE TITLE
getBounds overload

### ISSUE THREAD

**Issue by fab-girard** [MazeMap/Leaflet.ControlledBounds#2]
Hello,
first thanks for your interesting plugin!
I've seen the function getBounds is referenced 2 times in js. Not sure it is what you wanted to write.

Fabien

**Comment by IvanSanchez** [comment]
Yeah, that should be a mistake. Can you try with just the second definition, and make a pull request?

**Comment by IvanSanchez** [comment]
Fixed in #4
